enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    DOT, COMMA,
    STAR, SLASH, PLUS, MINUS,
    SEMICOLON,
    EQUAL, EQUAL_EQUAL,
    BANG, BANG_EQUAL,
    LESS, LESS_EQUAL,
    GREATER, GREATER_EQUAL,

    STRING, NUMBER, IDENTIFIER,

    //KEYWORDS
    AND, CLASS, ELSE, FALSE,
    FOR, FUN, IF, NIL, OR, PRINT,
    RETURN, SUPER, THIS, TRUE, VAR, WHILE,

    EOF
}